name: Drodo

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run RDP + Tailscale
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: cmd /c start.bat

      - name: Keep RDP Alive
        run: cmd /c loop.bat
