name: Drodo
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure Windows RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Install & Connect Tailscale
      run: cmd /c start.bat
      env:
        TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}

    - name: Keep RDP Alive
      run: cmd /c loop.bat
